/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    districts: District;
    constructions: Construction;
    'construction-changelog': ConstructionChangelog;
    suggestions: Suggestion;
    media: Media;
  };
  globals: {};
}

export interface User {
  id: string;
  email: string;
  name: string;
  role: 'contributor' | 'moderator' | 'admin';
  reputation?: number | null;
  bio?: string | null;
  avatar?: string | Media | null;
  _verified?: boolean | null;
  createdAt: string;
  updatedAt: string;
}

export interface District {
  id: string;
  name: string;
  nameEn?: string | null;
  code?: string | null;
  geometry?: Record<string, unknown> | null;
  createdAt: string;
  updatedAt: string;
}

export interface Construction {
  id: string;
  title: string;
  slug?: string | null;
  description?: Record<string, unknown>[] | null;
  constructionType: 'road' | 'highway' | 'metro' | 'bridge' | 'tunnel' | 'interchange' | 'station' | 'other';
  constructionStatus: 'planned' | 'in-progress' | 'completed' | 'paused' | 'cancelled';
  progress?: number | null;
  geometry?: Record<string, unknown> | null;
  centroid?: Record<string, unknown> | null;
  announcedDate?: string | null;
  startDate?: string | null;
  expectedEndDate?: string | null;
  actualEndDate?: string | null;
  details?: {
    contractor?: string | null;
    budget?: number | null;
    fundingSource?: string | null;
  };
  district?: string | District | null;
  metroStations?: {
    name: string;
    nameEn?: string | null;
    location?: Record<string, unknown> | null;
    stationOrder?: number | null;
    stationStatus?: 'planned' | 'in-progress' | 'completed' | 'operational' | null;
    stationProgress?: number | null;
    openedAt?: string | null;
    id?: string | null;
  }[] | null;
  images?: {
    image?: string | Media | null;
    caption?: string | null;
    takenAt?: string | null;
    id?: string | null;
  }[] | null;
  sources?: {
    url: string;
    title?: string | null;
    publishedAt?: string | null;
    id?: string | null;
  }[] | null;
  currentVersion?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface ConstructionChangelog {
  id: string;
  title: string;
  construction: string | Construction;
  changeType: 'status' | 'progress' | 'timeline' | 'milestone' | 'news' | 'image' | 'budget' | 'other';
  description?: Record<string, unknown>[] | null;
  statusChange?: {
    previousStatus?: 'planned' | 'in-progress' | 'completed' | 'paused' | 'cancelled' | null;
    newStatus?: 'planned' | 'in-progress' | 'completed' | 'paused' | 'cancelled' | null;
  };
  progressChange?: {
    previousProgress?: number | null;
    newProgress?: number | null;
  };
  timelineChange?: {
    field?: 'startDate' | 'expectedEndDate' | 'actualEndDate' | null;
    previousDate?: string | null;
    newDate?: string | null;
  };
  milestone?: {
    milestoneName?: string | null;
    milestoneDate?: string | null;
  };
  source?: {
    url?: string | null;
    title?: string | null;
  };
  images?: {
    image?: string | Media | null;
    caption?: string | null;
    id?: string | null;
  }[] | null;
  eventDate: string;
  author?: string | User | null;
  createdAt: string;
  updatedAt: string;
}

export interface Suggestion {
  id: string;
  title: string;
  suggestionType: 'create' | 'update' | 'complete' | 'correction';
  construction?: string | Construction | null;
  proposedData: Record<string, unknown>;
  proposedGeometry?: Record<string, unknown> | null;
  locationDescription?: string | null;
  justification?: string | null;
  evidenceUrls?: {
    url: string;
    id?: string | null;
  }[] | null;
  status?: 'pending' | 'under_review' | 'changes_requested' | 'approved' | 'rejected' | 'merged' | 'superseded' | null;
  sourceType: 'community' | 'scraper' | 'api';
  sourceUrl?: string | null;
  sourceConfidence?: number | null;
  contentHash?: string | null;
  submittedBy?: string | User | null;
  assignedTo?: string | User | null;
  reviewedBy?: string | User | null;
  reviewedAt?: string | null;
  reviewNotes?: string | null;
  mergedAt?: string | null;
  mergedVersion?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface Media {
  id: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
  alt?: string | null;
  createdAt: string;
  updatedAt: string;
}
